### ISSUE TITLE
Petite incohérence dans la partie Underlyings de la formation Ember ?

### ISSUE THREAD

**Issue by aneveux** [bmeurant/bmeurant.github.io#16]
Hello !

Je déroule attentivement la formation Ember que tu as écrite (merci beaucoup !), et j'ai l'impression d'une petite incohérence dans [cette partie](http://baptiste.meurant.io/ember/training/underlyings/) quand tu parles des propriétés calculées.

En effet tu notes : 

```
Les deux syntaxes sont strictement équivalentes. Il est cependant conseillé d’utiliser la première version qui n’utilise pas la réécriture du prototype de function (cf. documentation)
```

Et pourtant dans les exemples qui suivent, tu utilises la notation `.property('title', 'authors')` au lieu de la première notation illustrée : `Ember.computed`. (dans plusieurs exemples d'ailleurs).

Du fait : doit-on vraiment suivre la notation 1, ou la 2 est-elle finalement plus pratique ? :D

**Comment by bmeurant** [comment]
C'est pas faux ;-)

Les deux syntaxes sont effectivement équivalentes d'un point de vue fonctionnement et c'est d'ailleurs évidemment le même code qui est exécuté.

La première est moins verbeuse et peut-être plus évidente à écrire et c'est sans doute pour cela qu'elle est utilisée par la suite.

Néanmoins, elle repose sur le fait qu'Ember permet par défaut d'utiliser des APIs enrichies en étendant les prototypes JavaScript, ce qui, en fonction des cas, n'est pas forcément une bonne pratique (collisions de libs, etc.). On peut donc généralement conseiller d'utiliser la seconde, plus explicite et basée sur `Ember.computed`.

Dans tous les cas, autoriser ou non l'extension de prototype est une convention à déterminer au démarrage du projet. Il faut ensuite s'y tenir. Pour une app, c'est envisageable, pour une lib, un addon, la notation sans extension de prototype est à privilégier pour des raisons de compatibilités (notamment avec les apps qui l'interdisent).

Plus d'infos : https://guides.emberjs.com/v2.12.0/configuring-ember/disabling-prototype-extensions/

Merci du retour. J'espère que c'est plus clair. Je vais réfléchir à la manière de rendre ça plus cohérent
